import type { User, Recruitment, Application, Promotion } from './types';

export const users: User[] = [
  {
    id: '1',
    firstName: 'Admin',
    lastName: 'User',
    email: 'admin@university.edu',
    phone: '+1234567890',
    role: 'admin',
    department: 'Administration',
    designation: 'System Administrator',
    dateOfEmployment: new Date('2020-01-15'),
    promotionStatus: 'not_applicable',
    currentLevel: 'Level 5',
    resumeUrl: '/resumes/admin-user.pdf',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    firstName: 'Staff',
    lastName: 'Member',
    email: 'staff@university.edu',
    phone: '+1234567891',
    role: 'staff',
    department: 'Computer Science',
    designation: 'Assistant Professor',
    dateOfEmployment: new Date('2021-08-01'),
    promotionStatus: 'eligible',
    currentLevel: 'Level 3',
    resumeUrl: '/resumes/staff-member.pdf',
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    id: '3',
    firstName: 'Dr. Evelyn',
    lastName: 'Reed',
    email: 'evelyn.reed@university.edu',
    phone: '+1234567892',
    role: 'staff',
    department: 'Biology',
    designation: 'Associate Professor',
    dateOfEmployment: new Date('2019-09-01'),
    promotionStatus: 'pending',
    currentLevel: 'Level 4',
    resumeUrl: '/resumes/evelyn-reed.pdf',
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
  {
    id: '4',
    firstName: 'Prof. Samuel',
    lastName: 'Grant',
    email: 'samuel.grant@university.edu',
    phone: '+1234567893',
    role: 'staff',
    department: 'Mathematics',
    designation: 'Assistant Professor',
    dateOfEmployment: new Date('2022-01-15'),
    promotionStatus: 'eligible',
    currentLevel: 'Level 2',
    resumeUrl: '/resumes/samuel-grant.pdf',
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-04T00:00:00Z',
  },
  {
    id: '5',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@email.com',
    phone: '+1234567894',
    role: 'user',
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const recruitments: Recruitment[] = [
  {
    id: 'rec1',
    title: 'Professor of Computer Science',
    department: 'Computer Science',
    description: 'We are seeking a qualified Professor to join our Computer Science department.',
    requirements: ['PhD in Computer Science', 'Research experience', 'Teaching experience'],
    closingDate: '2024-08-15',
    status: 'open',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'rec2',
    title: 'Research Assistant',
    department: 'Biology',
    description: 'Research position in molecular biology laboratory.',
    requirements: ['Masters in Biology', 'Lab experience', 'Research publications'],
    closingDate: '2024-07-30',
    status: 'open',
    createdAt: '2024-06-05T00:00:00Z',
    updatedAt: '2024-06-05T00:00:00Z',
  },
  {
    id: 'rec3',
    title: 'Administrative Officer',
    department: 'Administration',
    description: 'Administrative support role for university operations.',
    requirements: ['Bachelor degree', 'Administrative experience', 'Communication skills'],
    closingDate: '2024-07-20',
    status: 'closed',
    createdAt: '2024-05-15T00:00:00Z',
    updatedAt: '2024-07-20T00:00:00Z',
  },
];

export const applications: Application[] = [
  {
    id: 'app1',
    recruitmentId: 'rec1',
    applicantName: 'John Doe',
    email: 'john.doe@email.com',
    resumeUrl: '/resumes/john-doe.pdf',
    coverLetter: 'I am very interested in this position and believe my skills align well with the requirements.',
    status: 'submitted',
    createdAt: '2024-06-10T10:00:00Z',
    updatedAt: '2024-06-10T10:00:00Z',
  },
  {
    id: 'app2',
    recruitmentId: 'rec2',
    applicantName: 'Jane Smith',
    email: 'jane.smith@email.com',
    resumeUrl: '/resumes/jane-smith.pdf',
    coverLetter: 'I have extensive experience in research and would love to contribute to your team.',
    status: 'reviewed',
    createdAt: '2024-06-12T14:30:00Z',
    updatedAt: '2024-06-15T09:15:00Z',
  },
  {
    id: 'app3',
    recruitmentId: 'rec3',
    applicantName: 'Bob Wilson',
    email: 'bob.wilson@email.com',
    resumeUrl: '/resumes/bob-wilson.pdf',
    coverLetter: 'My background in administration makes me a perfect fit for this role.',
    status: 'rejected',
    createdAt: '2024-06-14T16:45:00Z',
    updatedAt: '2024-06-16T11:20:00Z',
  },
];

export const promotions: Promotion[] = [
  {
    id: 'pro1',
    staffId: '3',
    staffName: 'Dr. Evelyn Reed',
    currentPosition: 'Associate Professor',
    newPosition: 'Full Professor',
    requestDate: '2024-06-15',
    status: 'approved',
    createdAt: '2024-06-15T00:00:00Z',
    updatedAt: '2024-06-20T00:00:00Z',
  },
  {
    id: 'pro2',
    staffId: '4',
    staffName: 'Prof. Samuel Grant',
    currentPosition: 'Assistant Professor',
    newPosition: 'Associate Professor',
    requestDate: '2024-07-05',
    status: 'pending',
    createdAt: '2024-07-05T00:00:00Z',
    updatedAt: '2024-07-05T00:00:00Z',
  },
];
